In [2]:
#SciKit Learn Preprocessing
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data=np.random.randint(0,100,(10,2))

In [5]:
data

array([[54, 19],
       [82, 87],
       [25, 69],
       [80, 40],
       [80, 78],
       [75, 70],
       [20, 43],
       [69, 94],
       [10, 42],
       [52, 94]])

In [46]:
data.shape

(10, 2)

In [6]:
#scaling Data for Neural Network...
scaler_model = MinMaxScaler()

In [7]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [8]:
scaler_model.fit(data)

/home/C00145769/.local/lib/python2.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scaler_model.transform(data)

array([[0.61111111, 0.        ],
       [1.        , 0.90666667],
       [0.20833333, 0.66666667],
       [0.97222222, 0.28      ],
       [0.97222222, 0.78666667],
       [0.90277778, 0.68      ],
       [0.13888889, 0.32      ],
       [0.81944444, 1.        ],
       [0.        , 0.30666667],
       [0.58333333, 1.        ]])

In [10]:
scaler_model.fit_transform(data)  #in one line

array([[0.61111111, 0.        ],
       [1.        , 0.90666667],
       [0.20833333, 0.66666667],
       [0.97222222, 0.28      ],
       [0.97222222, 0.78666667],
       [0.90277778, 0.68      ],
       [0.13888889, 0.32      ],
       [0.81944444, 1.        ],
       [0.        , 0.30666667],
       [0.58333333, 1.        ]])

In [11]:
#Splitting Data into 2 sets: Training and Data sets
import pandas as pd

In [12]:
dataf = pd.DataFrame (data=np.random.randint(0,101,(50,4)))  

In [33]:
dataf.head(10)

0    1   2   3
0  77   18  19  54
1  37  100  29   0
2  96   52  30  69
3  20   81  90  29
4  98   66  64  41
5  94   66  68  98
6  19   50  20  51
7  19   98  29  26
8  85   25   7  19
9  51   17  80  25

In [30]:
dataf.shape

(50, 4)

In [14]:
dataf0 = pd.DataFrame (data=np.random.randint(0,101,(50,4)), columns=['f1','f2','f3','label'])

In [45]:
dataf0.head(11)
#features, labels

f1  f2  f3  label
0   63  21  25      8
1   48  55  70     22
2   50  21  76     62
3   37  80  21     13
4   43  53  79      2
5   86  26  73     38
6    2  40  38      8
7   98  95  30     80
8   74  43  80     44
9   56  33  85     31
10  94  42  78     75

In [35]:
X=dataf0[['f1','f2','f3']]
type(X)

pandas.core.frame.DataFrame

In [36]:
dataf0.shape

(50, 4)

In [37]:
y=dataf0['label']
type(y)

pandas.core.series.Series

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
#train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [41]:
X_train.shape

(35, 3)

In [42]:
type(X_train)

pandas.core.frame.DataFrame

In [43]:
X_test.shape

(15, 3)